package com.migc.plugins

import io.ktor.server.plugins.callloging.*
import org.slf4j.event.*
import io.ktor.server.request.*
import io.ktor.server.application.*
import io.ktor.server.response.*

fun Application.configureMonitoring() {
    install(CallLogging)
//  Following two lines removed from original code generated by Ktor-generator
//        level = Level.INFO
//        filter { call -> call.request.path().startsWith("/") }
}
